### ISSUE TITLE
Zowimaoid neutral CAD files please

### ISSUE THREAD

**Issue by cparrapa** [bqlabs/zowi#18]
Hi @JavierIH can you please provide .stp or .igs neutral CAD files so i can work on top of that in other 3d software aside from freeCAD?, zowi/mods/Zowimaoid/

**Comment by JavierIH** [comment]
Hi, thank you for your feedback. I have generated steps, obj and stl files. They can be found here: https://github.com/bqlabs/zowi/tree/master/mods/Zowimanoid/parts

**Comment by cparrapa** [comment]
Perfect thanks for the quick response.
